DROP DATABASE IF EXISTS DBCOMPRAPARCELADA;
CREATE DATABASE DBCOMPRAPARCELADA;
USE DBCOMPRAPARCELADA;

CREATE TABLE COMPRA (
	IDCOMPRA INT NOT NULL AUTO_INCREMENT
	, VALOR_TOTAL NUMERIC(8,2)
	, QTDE_PARCELA INT
	, DT_COMPRA DATE
	, PRIMARY KEY (IDCOMPRA)
);

CREATE TABLE PARCELA(
	IDPARCELA INT NOT NULL AUTO_INCREMENT
    	, IDCOMPRA INT NOT NULL
    	, NUMERO INT
    	, DT_VENCIMENTO DATE
    	, VALOR NUMERIC(8,2)
    	, PRIMARY KEY (IDPARCELA)
    	, FOREIGN KEY (IDCOMPRA) REFERENCES COMPRA (IDCOMPRA)
);

DELIMITER $$

CREATE PROCEDURE SP_GERARCOMPRA(pVALOR NUMERIC(8,2), pQTDE_PARCELA INT, pDIA_VENDICMENTO INT)
BEGIN
	DECLARE vIDCOMPRA INT;
    DECLARE vPARCELA INT;
    DECLARE vVALORPARCELA NUMERIC(8,2);
    DECLARE vVENCIMENTO DATE;
    DECLARE vIDULTIMA_PARCELA INT;
    DECLARE vVALOR_DIFERENCA NUMERIC(8,2);

	-- INCLUINDO COMPRA
    INSERT INTO COMPRA (VALOR_TOTAL, QTDE_PARCELA, DT_COMPRA)VALUES(pVALOR, pQTDE_PARCELA, NOW());
    
    -- OBTENDO O ID GERADO
    SET vIDCOMPRA = LAST_INSERT_ID();

    SET vPARCELA = 1;

    -- CALCULANDO O VALOR DA PARCELA
    SET vVALORPARCELA = pVALOR / pQTDE_PARCELA;

	WHILE vPARCELA <= pQTDE_PARCELA DO

		-- CALCULANDO O VENCIMENTO DA PROXIMA PARCELA
		SET vVENCIMENTO = LAST_DAY(NOW());
		SET vVENCIMENTO = DATE_ADD(vVENCIMENTO, INTERVAL pDIA_VENDICMENTO DAY);
		SET vVENCIMENTO = DATE_ADD(vVENCIMENTO, INTERVAL vPARCELA - 1 month);

        INSERT INTO PARCELA (IDCOMPRA, NUMERO, VALOR, DT_VENCIMENTO)
        VALUES (vIDCOMPRA, vPARCELA, vVALORPARCELA, vVENCIMENTO);

        SET vPARCELA = vPARCELA + 1;

	END WHILE;
    
    SELECT pVALOR - SUM(VALOR), MAX(IDPARCELA)
    INTO vVALOR_DIFERENCA, vIDULTIMA_PARCELA
    FROM PARCELA 
    WHERE IDCOMPRA = vIDCOMPRA;
    
    UPDATE PARCELA
	SET VALOR = VALOR + vVALOR_DIFERENCA
    WHERE IDPARCELA = vIDULTIMA_PARCELA;
	
END $$

DELIMITER ;

CALL SP_GERARCOMPRA(130000, 360, 29);

SELECT * FROM COMPRA;
SELECT SUM(VALOR), MAX(IDPARCELA) FROM PARCELA WHERE IDCOMPRA = 1;
SELECT * FROM PARCELA WHERE IDCOMPRA = 1 ORDER BY IDPARCELA DESC;







