-- APAGANDO O BANCO DE DADOS CASO EXISTA
DROP DATABASE IF EXISTS DBEXERCICIO18;

-- CRIANDO O BANCO DE DADOS
CREATE DATABASE DBEXERCICIO18;

-- CONECTANDO NA BASE DE DADOS
USE DBEXERCICIO18;

-- CRIANDO AS TABELAS
CREATE TABLE DEPARTAMENTO (
	IDDEPARTAMENTO INT NOT NULL
    , NOME VARCHAR(45)
    , RAMAL INT
    , IDDEPARTAMENTO_RESPONSAVEL INT
    , PRIMARY KEY (IDDEPARTAMENTO)
    , FOREIGN KEY (IDDEPARTAMENTO_RESPONSAVEL) REFERENCES DEPARTAMENTO(IDDEPARTAMENTO)
);

CREATE TABLE FUNCIONARIO (
	IDFUNCIONARIO INT NOT NULL
    , IDDEPARTAMENTO INT NOT NULL
    , NOME VARCHAR(45)
    , DTADMISSAO DATE
    , TELEFONE VARCHAR(15)
    , PRIMARY KEY (IDFUNCIONARIO)
    , FOREIGN KEY (IDDEPARTAMENTO) REFERENCES DEPARTAMENTO(IDDEPARTAMENTO)
);